### ISSUE TITLE
Not working. It does not listen to the port.

### ISSUE THREAD

**Issue by home409ca** [nfriess/carrier_infinity#2]
Thank you for creating a plugin for HA, however, I have a problem with it.

HA is installed on an Oracle virtual machine.
HA version:

`Home Assistant 2022.9.7
Supervisor 2022.09.1
Operating System 9.0
Interfejs użytkownika: 20220907.2 - latest`

Unfortunately, I don't know why it doesn't work. I set the proxy on the thermostat as IP HA, and proxy 5000. I uploaded the files to a folder: "custom_components", I pasted the settings into "configuration.yaml".

When adding a card to the dashboard, I can't see the entities. I searched for "carrier", "climate", "infinity". So I don't know if the plugin is visible by HA at all.

I started SSH and checked if the port is listening. As far as I can see it is not doing so. 
![image](https://user-images.githubusercontent.com/114701129/193888883-84bfad92-15ce-42b2-8aea-cbb7ce95b013.png)
![image](https://user-images.githubusercontent.com/114701129/193904294-ac1c479f-4059-490d-82fb-42350a3b25d5.png)

Please help me...I care a lot about this plugin....

**Comment by nfriess** [comment]
Please review the log and it will tell you why the the component is not loading.  It is possible that it is not compatible with HA 2022.9.x because they changed the API for climate devices and I have not updated to the latest API yet.  (Specifically some constants for modes and presets were deprecated.)

**Comment by home409ca** [comment]
from supervisor logs - Core:
`2022-10-05 15:47:03.573 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform carrier_infinity is taking over 10 seconds.
2022-10-05 15:47:47.115 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: climate.carrier_infinity
2022-10-05 15:47:53.570 ERROR (MainThread) [homeassistant.components.climate] Setup of platform carrier_infinity is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2022-10-05 16:36:55.770 WARNING (SyncWorker_2) [custom_components.carrier_infinity.climate] Setup Failed on Timeout - Config.`

from HA logs:
`Logger: custom_components.carrier_infinity.climate
Source: custom_components/carrier_infinity/climate.py:168
Integration: carrier_infinity ([documentation](https://github.com/nfriess/carrier_infinity/blob/master/README.md))
First occurred: 16:36:55 (1 occurrences)
Last logged: 16:36:55

Setup Failed on Timeout - Config.`

`Logger: custom_components.carrier_infinity.climate
Source: custom_components/carrier_infinity/climate.py:168
Integration: carrier_infinity ([documentation](https://github.com/nfriess/carrier_infinity/blob/master/README.md))
First occurred: 16:36:55 (1 occurrences)
Last logged: 16:36:55

Setup Failed on Timeout - Config.`

`Logger: homeassistant.bootstrap
Source: bootstrap.py:441
First occurred: 15:47:47 (1 occurrences)
Last logged: 15:47:47

Waiting on integrations to complete setup: climate.carrier_infinity`

`Logger: homeassistant.components.climate
Source: runner.py:119
Integration: Klimat ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 15:47:03 (1 occurrences)
Last logged: 15:47:03

Setup of climate platform carrier_infinity is taking over 10 seconds.`

I ran the version on VM: Supervisor 2022.09.1
Operating System 8.5

I have uploaded the add-on and the problem is the same.
Log below.
`2022-10-05 17:32:59.751 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration carrier_infinity which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-05 17:33:02.468 ERROR (MainThread) [homeassistant.components.hassio.handler] /store return code 500
2022-10-05 17:33:02.480 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /store - 
2022-10-05 17:33:14.057 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform carrier_infinity is taking over 10 seconds.
2022-10-05 17:33:59.941 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: climate.carrier_infinity
2022-10-05 17:34:04.057 ERROR (MainThread) [homeassistant.components.climate] Setup of platform carrier_infinity is taking longer than 60 seconds. Startup will proceed without waiting any longer.
`

**Comment by nfriess** [comment]
The server starts listening on port 5000 before the message "Setup Failed on Timeout..." is printed, so that means that the server should have started and printed a message indicating that in the log just before the error message.

In your earlier screenshots you provided one where it did show that HA is listening on port 5000.  Perhaps you are using a docker image to run HA?  If so then you need to tell docker to expose the port to the host system.

From the log messages that you provided the plugin is starting correctly and it is waiting for the thermostat to check in and report its configuration and status so that the HA widget can be started with the information from the thermostat.  It can be tricky to get everything to start since sometimes the thermostat will take a long time to try to connect (once you have solved the problem with port 5000 not showing up on your host system).

**Comment by home409ca** [comment]
I use HA OS - virtualbox
https://www.home-assistant.io/installation/windows

Actually in Oralcle VirtualBox settings listening was disabled. I started it up and now I have this:
![image](https://user-images.githubusercontent.com/114701129/194382921-4961c3b5-f6b0-4687-b2d4-adb25490ec3f.png)

.237 is HA .165 is thermostat.

On the thermostat I no longer have the yellow icon on wifi - meaning it looks like it is working.. but.. I can't see the entities in HA. I searched for "carrier", "climate", "infinity". So I don't know if the plugin is visible by HA at all.

configuration.yaml:

> climate:
>   - platform: carrier_infinity
>     port: 5000
>     zone_names:
>       - zone_1
>     notify:
>       energy:
>         entity_id: pushover
>         title: Furnace Energy Report
>         message: Appended Report
>         data:
>           priority: 0
>           url: "https://www.home-assistant.io/"
>           #sound: pianobar
>           #attachment: "http://example.com/image.png"
>         delete:         #Deletes these DICT values before converting to YAML and sending.
>           - "@version"
>           - seer
>           - hspf
>           - cooling
>           - hpheat
>           - eheat
>           - gas
>           - reheat
>           - fangas
>           - fan
>           - looppump
>         muteable: True
> 

LOG:

> 2022-10-06 19:50:27.680 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform carrier_infinity is taking over 10 seconds.
> 2022-10-06 19:50:37.714 ERROR (MainThread) [homeassistant.components.climate] Error while setting up carrier_infinity platform for climate
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
> await asyncio.shield(task)
> File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
> result = self.fn(*self.args, **self.kwargs)
> File "/config/custom_components/carrier_infinity/climate.py", line 199, in setup_platform
> devices.append(_HTTPClientZone(_HTTPClient, zid, zone_name))
> File "/config/custom_components/carrier_infinity/climate.py", line 462, in __init__
> self.update()
> File "/config/custom_components/carrier_infinity/climate.py", line 583, in update
> activity_manual = next(
> File "/config/custom_components/carrier_infinity/climate.py", line 587, in <genexpr>
> if a["id"] == "manual"
> KeyError: 'id'

**Comment by nfriess** [comment]
The latest commit that I made on master will avoid this crash:
https://github.com/nfriess/carrier_infinity/commit/e8da9c5a631fac0064436c95f7308c8563d72791

Please try the version on master branch and hopefully that will get you going.

**Comment by home409ca** [comment]
This time another error:

> Logger: homeassistant.components.climate
> Source: runner.py:119
> Integration: Klimat ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
> First occurred: 16:19:50 (1 occurrences)
> Last logged: 16:19:50
> 
> Setup of climate platform carrier_infinity is taking over 10 seconds.

and

> Logger: homeassistant.components.websocket_api.http.connection
> Source: helpers/service.py:655
> Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
> First occurred: 16:23:49 (2 occurrences)
> Last logged: 16:23:54
> 
> [139636462378944] Entity climate.carrier_infinity_zone_1 does not support this service.
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 202, in handle_call_service
>     await hass.services.async_call(
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
>     task.result()
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
>     await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 207, in handle_service
>     await service.entity_service_call(
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 655, in entity_service_call
>     raise HomeAssistantError(
> homeassistant.exceptions.HomeAssistantError: Entity climate.carrier_infinity_zone_1 does not support this service.

**Comment by nfriess** [comment]
The first message is normal.  It takes at least 1-2 minutes until the thermostat checks in and reports its configuration.  It looks like after 4 minutes that still hasn't happened so there still something wrong with the setup of the thermostat or network configuration.

The exception that you provided doesn't have any useful information as to who called that service or why.  If the thermostat hasn't checked in then things are not set up correctly yet.  If you try to click on anything in the web UI then it will throw exceptions because of this.  It looks like you still need to do more investigating as to why the thermostat isn't connecting to port 5000 on the HA server.

**Comment by home409ca** [comment]
I don't know what the problem is.
I used [infinitude](https://github.com/nebulous/infinitude)and it started working.

Unfortunately, it requires an additional installation...
